### ISSUE TITLE
Support  XML query statement

### ISSUE THREAD

**Issue by TranNgocKhoa** [cofedream/Cofe-Mybatis#1]
Hello,
I really appreciate because this plugin help me to solve `Could not autowired` problem.
But there is a problem in my project.

I have a `MyMapper` mapper interface in package `com.mypackage.mapper` and  `MyMapper.xml` in `recources/mapper` folder. But your plugin shows that `Statement insertSomething is not defined`.

Is there any solution for it?

Thank you!

**Comment by cofedream** [comment]
Whould mind show some code?
This message only show when you mapper.xml dont't defined insert statemet or method haven't `@Insert` annotation

**Comment by cofedream** [comment]
> Hello,
> I really appreciate because this plugin help me to solve `Could not autowired` problem.
> But there is a problem in my project.
> 
> I have a `MyMapper` mapper interface in package `com.mypackage.mapper` and `MyMapper.xml` in `recources/mapper` folder. But your plugin shows that `Statement insertSomething is not defined`.
> 
> Is there any solution for it?
> 
> Thank you!

Whould mind show some code?
This message only show when your mapper.xml dont't defined insert statemet or method haven't `@Insert` annotation

**Comment by TranNgocKhoa** [comment]
Sorry, I don't know why but today when I open project again, the error is disappear.
But there is a problem when I using `resultMap` to map result to a collection of `String`. Here is my code:

```
<resultMap id="roleMap" type="com.example.mybatis.Role">
        <id property="roleId" column="role_id" />
        <result property="roleName" column="role_name" />
        <collection property="authorities" ofType="java.lang.String">
            <result property="path" column="authority" />
        </collection>
    </resultMap>
```
in line `<result property="path" column="authority" />`, **path** is shown as an error with message: `Could not find field path`.
I hope you can check it in next release.
Thank you so much!

**Comment by cofedream** [comment]
> Sorry, I don't know why but today when I open project again, the error is disappear.
> But there is a problem when I using `resultMap` to map result to a collection of `String`. Here is my code:
> 
> ```
> <resultMap id="roleMap" type="com.example.mybatis.Role">
>         <id property="roleId" column="role_id" />
>         <result property="roleName" column="role_name" />
>         <collection property="authorities" ofType="java.lang.String">
>             <result property="path" column="authority" />
>         </collection>
>     </resultMap>
> ```
> 
> in line `<result property="path" column="authority" />`, **path** is shown as an error with message: `Could not find field path`.
> I hope you can check it in next release.
> Thank you so much!

Thank you for your submission problem, I will fix it in the next version.
